# Generated by Django 6.0.5 on 2026-05-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='clips/')),
                ('index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(upload_to='exports/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='uploads/')),
                ('clips_count', models.IntegerField(default=5)),
                ('clip_duration', models.IntegerField(default=15)),
                ('aspect_ratio', models.CharField(choices=[('9:16', '9:16'), ('1:1', '1:1'), ('16:9', '16:9')], default='9:16', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.TextField()),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clip')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessedVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='processed/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clip')),
            ],
        ),
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.clip')),
            ],
        ),
        migrations.AddField(
            model_name='clip',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.videoupload'),
        ),
    ]
